server:
  port: ${SERVER_PORT:9020}
file:
  upload:
    path: /home/output_doc
spring:
  application:
    name: output-mapping-service
  zipkin:
    base-url: ${ZIPKIN_SERVER_URL:http://localhost:9411/}

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_SERVER_URL:http://localhost:9030}

  data:
    mongodb:
      host: output-mapping-service-db
      #host: 127.0.0.1
      port: 27019
      database: intecon

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:9070}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
